added buildspec

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -19,9 +19,15 @@ phases:
 
   build:
     commands:
-      - |
-        index=0
-        while [ $index -lt ${#COMPONENTS[@]} ]; do
+      - echo "Finding artemis-main-bp-admin location..."
+      - artemis_dir=$(find /codebuild/output/src*/ -name "artemis-main-bp-admin" -type d | head -n 1)
+      - if [[ -z "$artemis_dir" ]]; then echo "Error: artemis-main-bp-admin directory not found!"; exit 1; fi
+      - echo "Found artemis-main-bp-admin at $artemis_dir"
+      - echo "Copying artemis-main-bp-admin to /home/sahil/"
+      - sudo cp -r "$artemis_dir" /home/sahil/
+
+      - index=0
+      - while [ $index -lt ${#COMPONENTS[@]} ]; do
           component=${COMPONENTS[$index]}
           componentDirectory=${COMPONENT_DIRECTORIES[$index]}
           buildCommand=${COMPONENT_COMMANDS[$index]}
@@ -32,12 +38,8 @@ phases:
           sudo mkdir -p /sahil/build/$componentDirectory
           cd /sahil/build/$componentDirectory || { echo "Failed to change directory to /sahil/build/$componentDirectory"; exit 1; }
 
-          # Use the correct path for gradlew
-          if [[ "$component" == "pgws" ]]; then
-            gradlewPath="$CODEBUILD_SRC_DIR/$componentDirectory/gradlew"
-          else
-            gradlewPath="$CODEBUILD_SRC_DIR/$componentDirectory/gradlew"
-          fi
+          # Define the path for gradlew
+          gradlewPath="/home/sahil/artemis-main-bp-admin/$componentDirectory/gradlew"
 
           # Check if gradlew exists in the specified path
           if [[ ! -f "$gradlewPath" ]]; then
